#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt
import sys

if len(sys.argv) < 2:
    print("Usage: plot <file1> [-s] [file2] [-s] [file3] [-s] ...")
    print("     Files are csv with x0,y0,[z0],x1,y1,[z1]... headers")
    print("     -s option will plot as scatter plot instead of line")
    sys.exit(1)

filenames = []
plottypes = []
for arg in sys.argv[1:]:
    if arg == '-s':
        plottypes[-1] = 's'
    else:
        filenames.append(arg)
        plottypes.append('l')

num_entries = []
dimension = 2

data = []
for i,filename in enumerate(filenames):
    filedata = np.genfromtxt(filename, delimiter=',', names=True)
    data.append(filedata)
    if len(filedata.dtype.names) > 2:
        if filedata.dtype.names[2][0] == 'z':
            dimension = 3
    num_entries.append(int(len(filedata.dtype.names)/dimension))

fig = plt.figure()
ax = fig.add_subplot()
if dimension == 3:
    ax = fig.add_subplot(projection='3d')

for i,fd in enumerate(data):
    fd = np.array(fd.tolist())
    dd = np.hsplit(fd, num_entries[i])
    for d in dd:
        if plottypes[i] == 'l':
            if dimension == 3:
                ax.plot(d[0:,0], d[0:,1], d[0:,2])
            else:
                ax.plot(d[0:,0], d[0:,1])
        else:
            if dimension == 3:
                ax.scatter(d[0:,0], d[0:,1], d[0:,2], s=1, c=ax._get_lines.get_next_color())
            else:
                ax.scatter(d[0:,0], d[0:,1], s=1, c=ax._get_lines.get_next_color())

plt.show()
