#!/usr/bin/env bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
BUILD_DIR=$SCRIPT_DIR/../build/
BATCH_BUILD_DIR=$BUILD_DIR/Batched
STREAM_BUILD_DIR=$BUILD_DIR/BatchedWithStreams
OUTPUT_DIR=$SCRIPT_DIR/../output
INPUT_DIR=$SCRIPT_DIR/../input

if [ ! -d "$INPUT_DIR" ]; then
	echo "Missing Input Dir: $INPUT_DIR"
	echo "Use provided scripts to generate test data"
	exit 1
fi

mkdir -p $OUTPUT_DIR

# Batched
qsub -N test1 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=1,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test2 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=2,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test4 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=4,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test8 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=8,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test16 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=16,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test32 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=32,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test64 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=64,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test128 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=128,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test256 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=256,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test512 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=512,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test1024 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=1024,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test2048 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=2048,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test4096 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=4096,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test8192 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=8192,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test16384 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=16384,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test32768 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=32768,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs
qsub -N test65536 -v "PROGRAM=$BATCH_BUILD_DIR/test,N=65536,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR" $SCRIPT_DIR/runBatched.pbs

# Pipe Batched With Streams, run with 1,2,4,8,16,32,64,128 pipes
for i in {0..7}; do
	qsub -N test1 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=1,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test2 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=2,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test4 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=4,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test8 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=8,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test16 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=16,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test32 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=32,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test64 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=64,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test128 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=128,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test256 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=256,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test512 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=512,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test1024 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=1024,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test2048 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=2048,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test4096 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=4096,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test8192 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=8192,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test16384 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=16384,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test32768 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=32768,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
	qsub -N test65536 -v "PROGRAM=$STREAM_BUILD_DIR/test,N=65536,OUTPUT_DIR=$OUTPUT_DIR,INPUT_DIR=$INPUT_DIR,PIPES=$((2**i))" $SCRIPT_DIR/runBatchedWithStreams.pbs
done
